//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace odec.CP.Server.Model.Work.Migrations {
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class _201603312249402_PortfolioInitial {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        internal _201603312249402_PortfolioInitial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("odec.CP.Server.Model.Work.Migrations.201603312249402_PortfolioInitial", typeof(_201603312249402_PortfolioInitial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0dXW/cuPG9QP+DsE9tkdu1HbS4BvYdfHbcGs2H4U2ufQtoLW2r0Up7kjaxUfSX9aE/qX+hpERJ/BhSpD53c4sAwVokhzPDGXI0HM387z//Pf3xaR16X3CSBnF0NjueH808HPnxKogezmbb7P6772c//vDb35y+Xq2fvJ/Lfi9pPzIySs9mj1m2ebVYpP4jXqN0vg78JE7j+2zux+sFWsWLk6OjPy+OjxeYgJgRWJ53eruNsmCN8z/Inxdx5ONNtkXh23iFw5Q9Jy3LHKr3Dq1xukE+PpuRDv58iROC8zzvPf97nHyeExAZfsrSmXceBoigtcTh/cxDURRnKCNIv/qY4mWWxNHDckMeoPDD8waTfvcoTDEj5lXd3ZauoxNK16IeWILyt2kWrx0BHr9kjFrIw1uxe1YxkrDyNWF59kypztl5NruJk+w+DoP4OsPrmSfP+OoiTGhvLcuLtZoLYF54cOcXlewQEaP/XngX2zDbJvgswtss [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
