//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace odec.CP.Server.Model.Work.Migrations {
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class _201603312025237_WorkInitial {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        internal _201603312025237_WorkInitial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("odec.CP.Server.Model.Work.Migrations.201603312025237_WorkInitial", typeof(_201603312025237_WorkInitial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1dW2/kupF+XyD/odFPyWLitn2QIBnYCXx8SYx4Zgy35yRvBq2mbWF06UjqGRuL/WX7sD9p/8KSuvF+kyip26cxwMAtksUq8iNZJKuK//c//3vy19c4mn2HWR6myen86OBwPoNJkK7C5Pl0vimefv+n+V//8pv/OLlcxa+zX5p8P+F8qGSSn85fimL9cbHIgxcYg/wgDoMszdOn4iBI4wVYpYvjw8M/L46OFhCRmCNas9nJ3SYpwhiWP9DP8zQJ4LrYgOhTuoJRXn9HKcuS6uwziGG+BgE8naMMwcESZojngzL3wT/T7NsBIlHA1yKfz86iECC2ljB6ms9AkqQFKBDTH7/mcFlkafK8XKMPILp/W0OU7wlEOayF+Uiy28p1eIzlWpCCDalgkxdp7Ejw6Ke6oRZ88U7NPW8bEjXlJWry4g1LXTbn6fwcFPA5zd7mM76yj+dRhjMqW7vqpoOGwoeZPN+HFjEIWPjfh9n5Jio2GTxN4KbI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
